-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgrmWMIa6MzubEFXhK
Clrcgh4K/AV6OtVkbOWJWvSIhC+gCgYIKoZIzj0DAQehRANCAATyF96xwNSZD5XK
pSGwqvC9AD0FeEeAJDd3LNLJvurrTtZue3GHIVCGvwxhsB1S9DvpLJDB/SYQbI3W
patbHki8
-----END PRIVATE KEY-----